/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/
var a=Object.defineProperty;var t=Object.getOwnPropertyDescriptor;var c=Object.getOwnPropertyNames;var i=Object.prototype.hasOwnProperty;var m=(e,o)=>{for(var l in o)a(e,l,{get:o[l],enumerable:!0})},f=(e,o,l,n)=>{if(o&&typeof o=="object"||typeof o=="function")for(let d of c(o))!i.call(e,d)&&d!==l&&a(e,d,{get:()=>o[d],enumerable:!(n=t(o,d))||n.enumerable});return e};var p=e=>f(a({},"__esModule",{value:!0}),e);var x={};m(x,{default:()=>s});module.exports=p(x);var r=require("obsidian"),s=class extends r.Plugin{async onload(){console.log("JokerType loaded")}};
